# Generated by Django 2.2.3 on 2019-07-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='farmerId',
            field=models.CharField(max_length=20),
        ),
    ]
